### ISSUE TITLE
Rationalise hosted infrastructure

### ISSUE THREAD

**Issue by mor1** [me-box/databox#165]
Currently, various Databox components have dependencies on various hosted services for debugging or testing. We should rationalise these to ensure that the team has oversight of them, and to ensure that we're not at risk of mistakenly collecting people's data. References issue #161 

Services I'm aware of:

+ [ ] export.amar.io / [deployment Dockerfile](https://github.com/me-box-archive/extra-export-destination/pull/2)
+ [ ] store.iotdatabox.com
+ [ ] `core-oauth-intermediary` (not currently live?)
+ [ ] databox.amar.io
+ [ ] datashop.amar.io

Are there others?

**Comment by cgreenhalgh** [comment]
Potentially instances of [oauth intermediary](https://github.com/me-box/core-oauth-intermediary) (which should probably be platform- rather than core-) or similar for doing oauth for individual drivers for external APIs.

**Comment by Toshbrown** [comment]
There are a number of images related to the SDK which are currently stored outside of the databoxsystems repo. 

tlodge/databox-redis
tlodge/databox-datasource-mock
tlodge/databox-sdk
tlodge/databox-test-server

The code for all but databox-sdk is also not under the me-box organisation.

**Comment by mor1** [comment]
@tlodge Can you move the repos in question please? (Or perhaps they don't need to be?) 
Ping me when you do and I can make sure you're on the right team to continue modifying.

@cgreenhalgh I can see that `core-oauth-intermediary` will be useful, added to the list at the top. Is it currently running anywhere, or used by anything? What's the deployment model for it? Also, is it documented at all, other than the code?

**Comment by cgreenhalgh** [comment]
@mor1,

> @cgreenhalgh I can see that core-oauth-intermediary will be useful, added to the list at the top. Is it currently running anywhere, or used by anything? What's the deployment model for it? Also, is it documented at all, other than the code?

I'm not aware of any instance(s) or any documentation. Having been through the code it needs (a) small service-specific stub/adapter code written (e.g. service endpoints) and (b) instance-specific configuration (e.g. oauth client id and secret for specific oauth service app). Currently it has a stub for runkeeper.

In its current form I don't think it is ever so useful as any client can use it, and there is no logging and no scope for rate-limiting API requests. So I'm not convinced it is currently any better in practice than just "publishing" the client id and secret in the installable app image.

**Comment by mor1** [comment]
Ok-- finally looking at this now :) `export.amar.io` first.
If we have this service running, I can host it locally without a problem.
But first: is there a good reason why we need this running as a shared service, vs something that developers run themselves, locally, for testing purposes?
/cc @Toshbrown @yousefamar

**Comment by Toshbrown** [comment]
@mor1 IMHO the only reason to run a shared version is for demos and debugging. Devs should be exporting to their own servers once they are building their own apps. But its handy to have something to test against.

**Comment by mor1** [comment]
A publicly reachable version for demos makes sense, though I don't think we actually use it in any current demos do we? (And we should be building nicer demos than that anyway :)

The model in my head would be that, in development, you want to be interacting with a local (outside Databox but still local container) service rather than relying on network connectivity anyway. And we wouldn't want to be capturing data from other people by accident either.

Anyone else got a view?

**Comment by yousefamar** [comment]
@mor1 I concur; people can also just launch the export destination container locally for a fancier debug experience than tailing logs.

**Comment by cgreenhalgh** [comment]
I imagine we need something similar to export.amar.io for automated end-to-end smoke tests that is similar, but test-oriented.

**Comment by mor1** [comment]
@tlodge Looks like all the ones you needed to move have I think? Thanks! Has `databox-redis` gone away completely?

@Toshbrown Do we need to add http://databox.amar.io and http://datashop.amar.io to this list? They seem to be referenced in various repos.

@yousefamar Sorry, this fell off my stack. Could we perhaps put the export.amar.io service in a container so that developers can run their own copy locally for debug purposes, and so that (if we need to) we can host an instance somewhere? Ditto for `datashop.amar.io` and `databox.amar.io` (which appear to be giving 502 Bad Gateway also).

**Comment by yousefamar** [comment]
I think any references to `data(shop|box).amar.io` should be removed since the former is superseded by `store.iotdatabox.com` and the latter was just a thing that ran the latest databox version automatically for making sure everything works. It's defunct, but it might be worth having something like that?

For `export.amar.io`, there already is a Dockerfile, but how to deploy it is undocumented. Mainly would need to copy info from [here](https://github.com/me-box-archive/extra-export-destination/pull/2) into a readme, and all set. :+1:

**Comment by mor1** [comment]
ok, added to list. Dockerfile noted.

**Comment by tlodge** [comment]
@mort - sdk uses databox-redis, but it's just a vanilla docker redis
instance, so no repo!
