### ISSUE TITLE
Drivers and apps updated to core-store API

### ISSUE THREAD

**Issue by Toshbrown** [me-box/databox#200]
## Apps
 - [x] app-os-monitor
 - [x] app-twitter-sentiment
 - [ ] app-oaas
 - [x] app-light-graph

## Drivers 

 - [x] driver-sensingkit
 - [x] driver-twitter (almost see https://github.com/jptmoore/zest/issues/15 ✓)
 - [x] driver-google-takeout
 - [x] driver-os-monitor
 - [x] driver-phillips-hue
 - [x] driver-tplink-smart-plug
