### ISSUE TITLE
Update lib-[lang]-databox to core-store API

### ISSUE THREAD

**Issue by Toshbrown** [me-box/databox#201]
- [x] lib-node-databox
- [x] lib-go-databox
- [ ] lib-python-databox
