### ISSUE TITLE
Enable CI on all core repos

### ISSUE THREAD

**Issue by Toshbrown** [me-box/databox#55]
- [x]  databox
- [ ]  platform-app-server
- [ ]  core-container-manager 
- [x] core-arbiter 
- [x]  core-export-service see  https://github.com/me-box/core-export-service/commit/a83ba6ce8e98e41cf8017b521a66d24669e927c4
- [x]  store-json
